export type GeneratedDataClassification =
  | "runtime API source data"
  | "canonical generated reference data"
  | "server-internal source data"
  | "debug/report artifact"
  | "obsolete/unused candidate"
  | "unknown/manual review";

export type GeneratedDataDomain =
  | "crafting"
  | "FPS crafting"
  | "missions"
  | "mining/recommendations"
  | "lagrange/locations"
  | "refinery";

export type GeneratedDataAuthority =
  | "foundry"
  | "localization"
  | "ref_index"
  | "scintel-inferred"
  | "manual-override"
  | "external-import"
  | "mixed"
  | "unknown";

export type GeneratedDataConfidence = "high" | "medium" | "low" | "needs-validation";

export type GeneratedDataValidationStatus =
  | "not-needed"
  | "needs-source-audit"
  | "needs-mechanics-audit"
  | "needs-ingame-validation"
  | "validated";

export type GeneratedDataManifestEntry = {
  path: string;
  domain: GeneratedDataDomain;
  generatorScript: string;
  sourceInputsSummary: string;
  approximateSize: string;
  runtimeUsage: string;
  currentVisibility: "server-only" | "server-only reference, missing locally";
  recommendedFutureVisibility: "server-only" | "debug/reports" | "manual review";
  classification: GeneratedDataClassification;
  tooLargeForFrontendUse: boolean;
  containsDebugReportOrProvenanceFields: boolean;
  safePublicRemovalCandidate: boolean;
  futureOwnerApiOrRegistry: string;
  authority: GeneratedDataAuthority;
  confidence: GeneratedDataConfidence;
  externalDependency: boolean;
  externalSources?: readonly string[];
  comparisonSources?: readonly string[];
  validationStatus: GeneratedDataValidationStatus;
  notes?: string;
};

export const generatedDataManifest = [
  {
    path: "${SCINTEL_DATASET_ROOT}/crafting/blueprints.json",
    domain: "crafting",
    generatorScript: "D:/scintel/scripts/link/build_blueprint_api.py",
    sourceInputsSummary: "Foundry vehiclegear blueprint XML, crafted properties, reward pools, localization, material identity.",
    approximateSize: "3.63 MB",
    runtimeUsage: "Legacy source shaped into server-data/crafting/recipes and served by the crafting recipe API.",
    currentVisibility: "server-only",
    recommendedFutureVisibility: "server-only",
    classification: "runtime API source data",
    tooLargeForFrontendUse: true,
    containsDebugReportOrProvenanceFields: true,
    safePublicRemovalCandidate: false,
    futureOwnerApiOrRegistry: "crafting recipe API",
    authority: "mixed",
    confidence: "medium",
    externalDependency: false,
    validationStatus: "needs-source-audit",
    notes: "Foundry-derived with localization and Scintel material identity joins; source authority remains subject to audit while API consumers use the shaped recipe registry.",
  },
  {
    path: "${SCINTEL_DATASET_ROOT}/crafting/blueprint_rewards.json",
    domain: "crafting",
    generatorScript: "D:/scintel/scripts/link/build_blueprint_api.py",
    sourceInputsSummary: "Foundry crafting blueprint reward pool XML.",
    approximateSize: "0.12 MB",
    runtimeUsage: "No exact runtime fetch found in Moonbreaker.",
    currentVisibility: "server-only",
    recommendedFutureVisibility: "server-only",
    classification: "obsolete/unused candidate",
    tooLargeForFrontendUse: false,
    containsDebugReportOrProvenanceFields: true,
    safePublicRemovalCandidate: true,
    futureOwnerApiOrRegistry: "crafting blueprint source registry",
    authority: "foundry",
    confidence: "high",
    externalDependency: false,
    validationStatus: "not-needed",
    notes: "No exact runtime fetch found; keep only if a future blueprint source registry consumes it.",
  },
  {
    path: "${SCINTEL_COMPONENT_CARD_SOURCE:-${SCINTEL_DATASET_ROOT}/crafting/component_card_index.json}",
    domain: "crafting",
    generatorScript: "D:/scintel/scripts/generate-component-card-index.ts",
    sourceInputsSummary: "Published vehicle/FPS blueprints plus Foundry component stat records and localization.",
    approximateSize: "13.18 MB",
    runtimeUsage: "Legacy source shaped into server-data/crafting/component-cards and served by the component-card API.",
    currentVisibility: "server-only",
    recommendedFutureVisibility: "server-only",
    classification: "runtime API source data",
    tooLargeForFrontendUse: true,
    containsDebugReportOrProvenanceFields: true,
    safePublicRemovalCandidate: false,
    futureOwnerApiOrRegistry: "component card API",
    authority: "mixed",
    confidence: "needs-validation",
    externalDependency: false,
    comparisonSources: ["SPViewer", "Erkul"],
    validationStatus: "needs-source-audit",
    notes: "Foundry stat extraction and fitting/combat mechanics coverage are not complete manifest domains yet; add future entries before SPViewer/Erkul replacement decisions.",
  },
  {
    path: "server-data/crafting/reference/crafted-properties.json",
    domain: "crafting",
    generatorScript: "D:/scintel/scripts/link/build_blueprint_api.py",
    sourceInputsSummary: "Foundry crafting craftedproperties XML.",
    approximateSize: "0.01 MB",
    runtimeUsage: "Served from server-data/crafting/reference by the crafting reference API.",
    currentVisibility: "server-only",
    recommendedFutureVisibility: "server-only",
    classification: "runtime API source data",
    tooLargeForFrontendUse: false,
    containsDebugReportOrProvenanceFields: true,
    safePublicRemovalCandidate: false,
    futureOwnerApiOrRegistry: "crafting property registry",
    authority: "foundry",
    confidence: "high",
    externalDependency: false,
    validationStatus: "not-needed",
  },
  {
    path: "server-data/crafting/reference/quality-quantization.json",
    domain: "crafting",
    generatorScript: "D:/scintel/scripts/link/build_blueprint_api.py and build_mining_material_sources.py",
    sourceInputsSummary: "Foundry crafting qualityquantization XML.",
    approximateSize: "0.04 MB",
    runtimeUsage: "Served from server-data/crafting/reference by the crafting reference API.",
    currentVisibility: "server-only",
    recommendedFutureVisibility: "server-only",
    classification: "canonical generated reference data",
    tooLargeForFrontendUse: false,
    containsDebugReportOrProvenanceFields: true,
    safePublicRemovalCandidate: false,
    futureOwnerApiOrRegistry: "quality quantization registry",
    authority: "foundry",
    confidence: "needs-validation",
    externalDependency: false,
    validationStatus: "needs-mechanics-audit",
    notes: "Threshold mechanics and quantization interpretation need source/mechanics audit before being treated as final gameplay truth.",
  },
  {
    path: "server-data/crafting/reference/material-quality-quantization.json",
    domain: "crafting",
    generatorScript: "D:/scintel/scripts/link/build_material_quality_quantization.py",
    sourceInputsSummary: "Foundry qualityquantization XML plus mining source material names.",
    approximateSize: "0.01 MB",
    runtimeUsage: "Served from server-data/crafting/reference by the crafting reference API.",
    currentVisibility: "server-only",
    recommendedFutureVisibility: "server-only",
    classification: "runtime API source data",
    tooLargeForFrontendUse: false,
    containsDebugReportOrProvenanceFields: false,
    safePublicRemovalCandidate: false,
    futureOwnerApiOrRegistry: "quality quantization registry",
    authority: "mixed",
    confidence: "needs-validation",
    externalDependency: false,
    validationStatus: "needs-mechanics-audit",
    notes: "User-facing quality options are Foundry-derived but material naming joins come from generated mining/material identity data.",
  },
  {
    path: "${SCINTEL_DATASET_ROOT}/crafting/material_quality_quantization_debug.json",
    domain: "crafting",
    generatorScript: "D:/scintel/scripts/link/build_material_quality_quantization.py",
    sourceInputsSummary: "Foundry qualityquantization XML with raw bands, source paths, warnings, and duplicate-value details.",
    approximateSize: "0.05 MB",
    runtimeUsage: "No runtime fetch found.",
    currentVisibility: "server-only",
    recommendedFutureVisibility: "debug/reports",
    classification: "debug/report artifact",
    tooLargeForFrontendUse: false,
    containsDebugReportOrProvenanceFields: true,
    safePublicRemovalCandidate: true,
    futureOwnerApiOrRegistry: "generated data reports",
    authority: "mixed",
    confidence: "needs-validation",
    externalDependency: false,
    validationStatus: "needs-mechanics-audit",
    notes: "Debug companion retained with the accepted Scintel snapshot; it is not a Moonbreaker runtime artifact.",
  },
  {
    path: "${SCINTEL_DATASET_ROOT}/crafting/material_quality_quantization_report.json",
    domain: "crafting",
    generatorScript: "D:/scintel/scripts/link/build_material_quality_quantization.py",
    sourceInputsSummary: "Quantization generation summary and warnings.",
    approximateSize: "0.00 MB",
    runtimeUsage: "No runtime fetch found.",
    currentVisibility: "server-only",
    recommendedFutureVisibility: "debug/reports",
    classification: "debug/report artifact",
    tooLargeForFrontendUse: false,
    containsDebugReportOrProvenanceFields: true,
    safePublicRemovalCandidate: true,
    futureOwnerApiOrRegistry: "generated data reports",
    authority: "mixed",
    confidence: "needs-validation",
    externalDependency: false,
    validationStatus: "needs-mechanics-audit",
    notes: "Report artifact for quantization generation; not runtime data.",
  },
  {
    path: "server-data/crafting/reference/material-identity-index.json",
    domain: "crafting",
    generatorScript: "D:/scintel/scripts/link/build_material_identity_index.py",
    sourceInputsSummary: "Quantization debug data, mining material sources, carryable entity records, and resource overrides.",
    approximateSize: "0.31 MB",
    runtimeUsage: "Served from server-data/crafting/reference by the crafting reference API.",
    currentVisibility: "server-only",
    recommendedFutureVisibility: "server-only",
    classification: "canonical generated reference data",
    tooLargeForFrontendUse: false,
    containsDebugReportOrProvenanceFields: true,
    safePublicRemovalCandidate: false,
    futureOwnerApiOrRegistry: "material identity registry",
    authority: "mixed",
    confidence: "medium",
    externalDependency: false,
    validationStatus: "needs-source-audit",
    notes: "Combines Foundry references, Scintel inference, and manual override bridges for material identity.",
  },
  {
    path: "${SCINTEL_DATASET_ROOT}/crafting/unresolved_resource_ids.json",
    domain: "crafting",
    generatorScript: "D:/scintel/scripts/link/build_blueprint_api.py",
    sourceInputsSummary: "Unresolved resource ids detected while parsing vehicle blueprints.",
    approximateSize: "0.00 MB",
    runtimeUsage: "No runtime fetch found.",
    currentVisibility: "server-only",
    recommendedFutureVisibility: "debug/reports",
    classification: "debug/report artifact",
    tooLargeForFrontendUse: false,
    containsDebugReportOrProvenanceFields: true,
    safePublicRemovalCandidate: true,
    futureOwnerApiOrRegistry: "generated data reports",
    authority: "scintel-inferred",
    confidence: "medium",
    externalDependency: false,
    validationStatus: "not-needed",
    notes: "Empty unresolved list/report artifact in current output.",
  },
  {
    path: "${SCINTEL_DATASET_ROOT}/crafting/fps/fps_blueprints.json",
    domain: "FPS crafting",
    generatorScript: "D:/scintel/scripts/link/build_fps_crafting_api.py and build_fps_variant_families.py",
    sourceInputsSummary: "Foundry FPS gear blueprint XML, localization, ref index, crafted properties, material identity.",
    approximateSize: "15.55 MB",
    runtimeUsage: "Legacy source shaped into server-data/crafting/recipes and served by the crafting recipe API.",
    currentVisibility: "server-only",
    recommendedFutureVisibility: "server-only",
    classification: "runtime API source data",
    tooLargeForFrontendUse: true,
    containsDebugReportOrProvenanceFields: true,
    safePublicRemovalCandidate: false,
    futureOwnerApiOrRegistry: "FPS crafting recipe API",
    authority: "mixed",
    confidence: "medium",
    externalDependency: false,
    comparisonSources: ["SPViewer", "Erkul"],
    validationStatus: "needs-source-audit",
    notes: "Foundry-derived FPS recipes with inferred variant/family metadata; fitting/combat replacement work requires future manifest entries.",
  },
  {
    path: "${SCINTEL_DATASET_ROOT}/crafting/fps/weapons.json",
    domain: "FPS crafting",
    generatorScript: "D:/scintel/scripts/link/build_fps_crafting_api.py and build_fps_variant_families.py",
    sourceInputsSummary: "Weapon subset derived from FPS blueprint records.",
    approximateSize: "3.23 MB",
    runtimeUsage: "No exact runtime fetch found.",
    currentVisibility: "server-only",
    recommendedFutureVisibility: "server-only",
    classification: "obsolete/unused candidate",
    tooLargeForFrontendUse: true,
    containsDebugReportOrProvenanceFields: true,
    safePublicRemovalCandidate: true,
    futureOwnerApiOrRegistry: "FPS crafting recipe API",
    authority: "mixed",
    confidence: "medium",
    externalDependency: false,
    comparisonSources: ["SPViewer", "Erkul"],
    validationStatus: "needs-source-audit",
    notes: "Subset of FPS blueprint data; no exact runtime fetch found.",
  },
  {
    path: "${SCINTEL_DATASET_ROOT}/crafting/fps/armor.json",
    domain: "FPS crafting",
    generatorScript: "D:/scintel/scripts/link/build_fps_crafting_api.py and build_fps_variant_families.py",
    sourceInputsSummary: "Armor subset derived from FPS blueprint records.",
    approximateSize: "12.08 MB",
    runtimeUsage: "No exact runtime fetch found.",
    currentVisibility: "server-only",
    recommendedFutureVisibility: "server-only",
    classification: "obsolete/unused candidate",
    tooLargeForFrontendUse: true,
    containsDebugReportOrProvenanceFields: true,
    safePublicRemovalCandidate: true,
    futureOwnerApiOrRegistry: "FPS crafting recipe API",
    authority: "mixed",
    confidence: "medium",
    externalDependency: false,
    comparisonSources: ["SPViewer", "Erkul"],
    validationStatus: "needs-source-audit",
    notes: "Subset of FPS blueprint data; no exact runtime fetch found.",
  },
  {
    path: "${SCINTEL_DATASET_ROOT}/crafting/fps/ammo.json",
    domain: "FPS crafting",
    generatorScript: "D:/scintel/scripts/link/build_fps_crafting_api.py",
    sourceInputsSummary: "Ammo subset derived from FPS blueprint records.",
    approximateSize: "0.22 MB",
    runtimeUsage: "No exact runtime fetch found.",
    currentVisibility: "server-only",
    recommendedFutureVisibility: "server-only",
    classification: "obsolete/unused candidate",
    tooLargeForFrontendUse: false,
    containsDebugReportOrProvenanceFields: true,
    safePublicRemovalCandidate: true,
    futureOwnerApiOrRegistry: "FPS crafting recipe API",
    authority: "mixed",
    confidence: "medium",
    externalDependency: false,
    comparisonSources: ["SPViewer", "Erkul"],
    validationStatus: "needs-source-audit",
    notes: "Subset of FPS blueprint data; no exact runtime fetch found.",
  },
  {
    path: "${SCINTEL_DATASET_ROOT}/crafting/fps/weapon_families.json",
    domain: "FPS crafting",
    generatorScript: "D:/scintel/scripts/link/build_fps_variant_families.py",
    sourceInputsSummary: "Post-processed visual grouping over FPS weapon blueprint records.",
    approximateSize: "3.47 MB",
    runtimeUsage: "No exact runtime fetch found.",
    currentVisibility: "server-only",
    recommendedFutureVisibility: "server-only",
    classification: "obsolete/unused candidate",
    tooLargeForFrontendUse: true,
    containsDebugReportOrProvenanceFields: true,
    safePublicRemovalCandidate: true,
    futureOwnerApiOrRegistry: "FPS crafting family registry",
    authority: "scintel-inferred",
    confidence: "needs-validation",
    externalDependency: false,
    comparisonSources: ["SPViewer", "Erkul"],
    validationStatus: "needs-source-audit",
    notes: "Visual grouping is inferred, not canonical Foundry authority.",
  },
  {
    path: "${SCINTEL_DATASET_ROOT}/crafting/fps/armor_families.json",
    domain: "FPS crafting",
    generatorScript: "D:/scintel/scripts/link/build_fps_variant_families.py",
    sourceInputsSummary: "Post-processed visual grouping over FPS armor blueprint records.",
    approximateSize: "12.59 MB",
    runtimeUsage: "No exact runtime fetch found.",
    currentVisibility: "server-only",
    recommendedFutureVisibility: "server-only",
    classification: "obsolete/unused candidate",
    tooLargeForFrontendUse: true,
    containsDebugReportOrProvenanceFields: true,
    safePublicRemovalCandidate: true,
    futureOwnerApiOrRegistry: "FPS crafting family registry",
    authority: "scintel-inferred",
    confidence: "needs-validation",
    externalDependency: false,
    comparisonSources: ["SPViewer", "Erkul"],
    validationStatus: "needs-source-audit",
    notes: "Visual grouping is inferred, not canonical Foundry authority.",
  },
  {
    path: "${SCINTEL_DATASET_ROOT}/crafting/fps/fps_variant_families.json",
    domain: "FPS crafting",
    generatorScript: "D:/scintel/scripts/link/build_fps_variant_families.py",
    sourceInputsSummary: "Combined FPS weapon and armor visual family records.",
    approximateSize: "16.06 MB",
    runtimeUsage: "No exact runtime fetch found.",
    currentVisibility: "server-only",
    recommendedFutureVisibility: "server-only",
    classification: "obsolete/unused candidate",
    tooLargeForFrontendUse: true,
    containsDebugReportOrProvenanceFields: true,
    safePublicRemovalCandidate: true,
    futureOwnerApiOrRegistry: "FPS crafting family registry",
    authority: "scintel-inferred",
    confidence: "needs-validation",
    externalDependency: false,
    comparisonSources: ["SPViewer", "Erkul"],
    validationStatus: "needs-source-audit",
    notes: "Visual grouping is inferred, not canonical Foundry authority.",
  },
  {
    path: "server-data/missions/source/mission_contracts.json",
    domain: "missions",
    generatorScript: "D:/scintel/scripts/link/build_mission_blueprint_rewards_api.py",
    sourceInputsSummary: "Foundry contractgenerator XML, factions, standings, reputation rewards, mission types, blueprint reward pools.",
    approximateSize: "47.70 MB",
    runtimeUsage: "Served from server-data/missions by routed mission APIs.",
    currentVisibility: "server-only",
    recommendedFutureVisibility: "server-only",
    classification: "runtime API source data",
    tooLargeForFrontendUse: true,
    containsDebugReportOrProvenanceFields: true,
    safePublicRemovalCandidate: false,
    futureOwnerApiOrRegistry: "mission browser API",
    authority: "mixed",
    confidence: "medium",
    externalDependency: false,
    validationStatus: "needs-source-audit",
    notes: "Foundry contract extraction with localization and blueprint reward joins; too large for direct frontend consumption.",
  },
  {
    path: "server-data/missions/source/mission_blueprint_rewards.json",
    domain: "missions",
    generatorScript: "D:/scintel/scripts/link/build_mission_blueprint_rewards_api.py",
    sourceInputsSummary: "Blueprint-rewarding mission subset built from contract generators and reward pools.",
    approximateSize: "16.61 MB",
    runtimeUsage: "Served from server-data/crafting/blueprint-sources by routed crafting APIs.",
    currentVisibility: "server-only",
    recommendedFutureVisibility: "server-only",
    classification: "runtime API source data",
    tooLargeForFrontendUse: true,
    containsDebugReportOrProvenanceFields: true,
    safePublicRemovalCandidate: false,
    futureOwnerApiOrRegistry: "blueprint source API",
    authority: "mixed",
    confidence: "medium",
    externalDependency: false,
    validationStatus: "needs-source-audit",
    notes: "Mission-source extraction from Foundry contracts and reward pools; should be shaped by blueprint source APIs.",
  },
  {
    path: "server-data/missions/source/blueprint_reward_sources.json",
    domain: "missions",
    generatorScript: "D:/scintel/scripts/link/build_mission_blueprint_rewards_api.py",
    sourceInputsSummary: "Reverse lookup from blueprint GUIDs to mission source records.",
    approximateSize: "4.43 MB",
    runtimeUsage: "Served from server-data/crafting/blueprint-sources by routed crafting APIs.",
    currentVisibility: "server-only",
    recommendedFutureVisibility: "server-only",
    classification: "runtime API source data",
    tooLargeForFrontendUse: true,
    containsDebugReportOrProvenanceFields: false,
    safePublicRemovalCandidate: false,
    futureOwnerApiOrRegistry: "blueprint source API",
    authority: "mixed",
    confidence: "medium",
    externalDependency: false,
    validationStatus: "needs-source-audit",
    notes: "Reverse lookup built from mission and blueprint reward joins.",
  },
  {
    path: "server-data/missions/source/mission_reward_lookups.json",
    domain: "missions",
    generatorScript: "D:/scintel/scripts/link/build_mission_blueprint_rewards_api.py",
    sourceInputsSummary: "Mission lookup tables for blueprint pools, factions, standings, reputation rewards, and mission types.",
    approximateSize: "0.62 MB",
    runtimeUsage: "Served from server-data/missions by routed mission APIs.",
    currentVisibility: "server-only",
    recommendedFutureVisibility: "server-only",
    classification: "runtime API source data",
    tooLargeForFrontendUse: false,
    containsDebugReportOrProvenanceFields: true,
    safePublicRemovalCandidate: false,
    futureOwnerApiOrRegistry: "mission browser API",
    authority: "mixed",
    confidence: "medium",
    externalDependency: false,
    validationStatus: "needs-source-audit",
    notes: "Lookup payload mixes Foundry records with localized display labels.",
  },
  {
    path: "server-data/missions/source/mission_extraction_report.json",
    domain: "missions",
    generatorScript: "D:/scintel/scripts/link/build_mission_blueprint_rewards_api.py",
    sourceInputsSummary: "Mission extraction counts, unresolved references, and validation metadata.",
    approximateSize: "0.01 MB",
    runtimeUsage: "Validated as a server-only Scintel mission source artifact.",
    currentVisibility: "server-only",
    recommendedFutureVisibility: "debug/reports",
    classification: "debug/report artifact",
    tooLargeForFrontendUse: false,
    containsDebugReportOrProvenanceFields: true,
    safePublicRemovalCandidate: true,
    futureOwnerApiOrRegistry: "generated data reports",
    authority: "mixed",
    confidence: "medium",
    externalDependency: false,
    validationStatus: "not-needed",
    notes: "Validation/report artifact; not a runtime contract.",
  },
  {
    path: "server-data/mining/indexes/location-material.json",
    domain: "mining/recommendations",
    generatorScript: "D:/scintel/scripts/link/build_mining_static_indexes.py plus scripts/update-pyro-location-indexes.mts",
    sourceInputsSummary: "Enriched mining material sources, spawn edges, Lagrange groups, and localization.",
    approximateSize: "1.18 MB",
    runtimeUsage: "Served from server-data/mining/indexes by routed mining APIs.",
    currentVisibility: "server-only",
    recommendedFutureVisibility: "server-only",
    classification: "server-internal source data",
    tooLargeForFrontendUse: true,
    containsDebugReportOrProvenanceFields: true,
    safePublicRemovalCandidate: false,
    futureOwnerApiOrRegistry: "mining recommender API",
    authority: "mixed",
    confidence: "needs-validation",
    externalDependency: false,
    validationStatus: "needs-mechanics-audit",
    notes: "Includes Scintel-inferred class resolution, source probability, method fit, and quality signals; scoring/threshold mechanics need audit.",
  },
  {
    path: "server-data/mining/indexes/material-encounter-rankings.json",
    domain: "mining/recommendations",
    generatorScript: "D:/scintel/scripts/link/build_mining_static_indexes.py plus scripts/update-pyro-location-indexes.mts",
    sourceInputsSummary: "Ranked material/location rows derived from static mining indexes.",
    approximateSize: "0.33 MB",
    runtimeUsage: "Served from server-data/mining/indexes by routed mining APIs.",
    currentVisibility: "server-only",
    recommendedFutureVisibility: "server-only",
    classification: "server-internal source data",
    tooLargeForFrontendUse: false,
    containsDebugReportOrProvenanceFields: false,
    safePublicRemovalCandidate: false,
    futureOwnerApiOrRegistry: "mining recommender API",
    authority: "scintel-inferred",
    confidence: "needs-validation",
    externalDependency: false,
    validationStatus: "needs-mechanics-audit",
    notes: "Ranking fields are derived from Scintel scoring and should be validated against intended mining mechanics.",
  },
  {
    path: "server-data/mining/indexes/material-quality.json",
    domain: "mining/recommendations",
    generatorScript: "D:/scintel/scripts/link/build_mining_static_indexes.py plus scripts/update-pyro-location-indexes.mts",
    sourceInputsSummary: "Material quality chance rows derived from static mining indexes.",
    approximateSize: "0.20 MB",
    runtimeUsage: "Served from server-data/mining/indexes by routed mining APIs.",
    currentVisibility: "server-only",
    recommendedFutureVisibility: "server-only",
    classification: "server-internal source data",
    tooLargeForFrontendUse: false,
    containsDebugReportOrProvenanceFields: false,
    safePublicRemovalCandidate: false,
    futureOwnerApiOrRegistry: "mining recommender API",
    authority: "mixed",
    confidence: "needs-validation",
    externalDependency: false,
    validationStatus: "needs-mechanics-audit",
    notes: "Quality thresholds are generated estimates; source and mechanics validation are still required.",
  },
  {
    path: "server-data/mining/indexes/location-distribution.json",
    domain: "mining/recommendations",
    generatorScript: "D:/scintel/scripts/link/build_mining_static_indexes.py plus scripts/update-pyro-location-indexes.mts",
    sourceInputsSummary: "Location mining-class distribution rows derived from spawn edges.",
    approximateSize: "0.03 MB",
    runtimeUsage: "Served from server-data/mining/indexes by routed mining APIs.",
    currentVisibility: "server-only",
    recommendedFutureVisibility: "server-only",
    classification: "server-internal source data",
    tooLargeForFrontendUse: false,
    containsDebugReportOrProvenanceFields: false,
    safePublicRemovalCandidate: false,
    futureOwnerApiOrRegistry: "mining recommender API",
    authority: "scintel-inferred",
    confidence: "needs-validation",
    externalDependency: false,
    validationStatus: "needs-mechanics-audit",
    notes: "Location method distribution is derived from spawn edges and class resolver logic.",
  },
  {
    path: "server-data/mining/indexes/location-hierarchy.json",
    domain: "mining/recommendations",
    generatorScript: "D:/scintel/scripts/link/build_mining_static_indexes.py",
    sourceInputsSummary: "Generated Lagrange groups folded into mining location hierarchy metadata.",
    approximateSize: "0.00 MB",
    runtimeUsage: "Served from server-data/mining/indexes by routed mining APIs.",
    currentVisibility: "server-only",
    recommendedFutureVisibility: "server-only",
    classification: "server-internal source data",
    tooLargeForFrontendUse: false,
    containsDebugReportOrProvenanceFields: false,
    safePublicRemovalCandidate: false,
    futureOwnerApiOrRegistry: "mining recommender API",
    authority: "mixed",
    confidence: "medium",
    externalDependency: false,
    validationStatus: "needs-source-audit",
    notes: "Hierarchy folds generated Lagrange grouping into mining indexes.",
  },
  {
    path: "server-data/mining/locations/lagrange-groups.json",
    domain: "lagrange/locations",
    generatorScript: "D:/scintel/scripts/generate-lagrange-api.mjs",
    sourceInputsSummary: "Localization global.ini grouped by Lagrange material signatures.",
    approximateSize: "0.01 MB",
    runtimeUsage: "Served from server-data/mining/indexes by routed mining APIs.",
    currentVisibility: "server-only",
    recommendedFutureVisibility: "server-only",
    classification: "server-internal source data",
    tooLargeForFrontendUse: false,
    containsDebugReportOrProvenanceFields: true,
    safePublicRemovalCandidate: false,
    futureOwnerApiOrRegistry: "location registry",
    authority: "localization",
    confidence: "medium",
    externalDependency: false,
    validationStatus: "needs-source-audit",
    notes: "Generated grouping uses localization labels and inferred material signatures; should be audited before becoming canonical location authority.",
  },
  {
    path: "server-data/mining/locations/lagrange-children.json",
    domain: "lagrange/locations",
    generatorScript: "D:/scintel/scripts/generate-lagrange-api.mjs",
    sourceInputsSummary: "Scintel ref_index StarMapObject records for Lagrange point children.",
    approximateSize: "0.37 MB",
    runtimeUsage: "Served from server-data/mining/indexes by routed mining APIs.",
    currentVisibility: "server-only",
    recommendedFutureVisibility: "server-only",
    classification: "server-internal source data",
    tooLargeForFrontendUse: false,
    containsDebugReportOrProvenanceFields: true,
    safePublicRemovalCandidate: false,
    futureOwnerApiOrRegistry: "location registry",
    authority: "ref_index",
    confidence: "medium",
    externalDependency: false,
    validationStatus: "needs-source-audit",
    notes: "Derived from ref_index StarMapObject records; includes provenance paths.",
  },
  {
    path: "server-data/crafting/reference/refinery-yields.json",
    domain: "refinery",
    generatorScript: "scripts/import-refinery-yields.mts",
    sourceInputsSummary: "UEX refinery yields CSV.",
    approximateSize: "0.01 MB",
    runtimeUsage: "Served from server-data/crafting/reference by the refinery reference API.",
    currentVisibility: "server-only",
    recommendedFutureVisibility: "server-only",
    classification: "canonical generated reference data",
    tooLargeForFrontendUse: false,
    containsDebugReportOrProvenanceFields: true,
    safePublicRemovalCandidate: false,
    futureOwnerApiOrRegistry: "refinery planner API",
    authority: "external-import",
    confidence: "needs-validation",
    externalDependency: true,
    externalSources: ["UEX", "manual CSV"],
    validationStatus: "needs-source-audit",
    notes: "Imported from a UEX CSV rather than Foundry authority; should be cross-checked before canonical gameplay claims.",
  },
  {
    path: "server-data/mining/recommender/material-source-scores.json",
    domain: "mining/recommendations",
    generatorScript: "D:/scintel/scripts/link/build_material_source_scores.py",
    sourceInputsSummary: "Mining material_sources.json, mineables.json, and location_material_index.json.",
    approximateSize: "0.55 MB",
    runtimeUsage: "Read by server/config/apiPaths.ts and server/recommender/loadApiData.ts.",
    currentVisibility: "server-only",
    recommendedFutureVisibility: "server-only",
    classification: "server-internal source data",
    tooLargeForFrontendUse: false,
    containsDebugReportOrProvenanceFields: true,
    safePublicRemovalCandidate: false,
    futureOwnerApiOrRegistry: "mining recommender API",
    authority: "scintel-inferred",
    confidence: "needs-validation",
    externalDependency: false,
    validationStatus: "needs-mechanics-audit",
    notes: "Server-only scored recommender source; scoring model remains independently auditable from the routed index projections.",
  },
  {
    path: "server-data/mining/recommender/material-sources-quality-enriched.json",
    domain: "mining/recommendations",
    generatorScript: "D:/scintel/scripts/link/enrich_material_source_quality.py",
    sourceInputsSummary: "Mining material_sources.json enriched with quality_distribution.json.",
    approximateSize: "1.49 MB",
    runtimeUsage: "Read by server/config/apiPaths.ts and server/recommender/loadApiData.ts.",
    currentVisibility: "server-only",
    recommendedFutureVisibility: "server-only",
    classification: "server-internal source data",
    tooLargeForFrontendUse: true,
    containsDebugReportOrProvenanceFields: true,
    safePublicRemovalCandidate: false,
    futureOwnerApiOrRegistry: "mining recommender API",
    authority: "mixed",
    confidence: "needs-validation",
    externalDependency: false,
    validationStatus: "needs-mechanics-audit",
    notes: "Quality enrichment combines Foundry quality distributions with Scintel matching heuristics.",
  },
  {
    path: "server-data/mining/recommender/location-metadata.json",
    domain: "mining/recommendations",
    generatorScript: "unknown/manual review",
    sourceInputsSummary: "Optional location metadata projection published with the mining recommender registry.",
    approximateSize: "unknown",
    runtimeUsage: "Read by server/recommender/loadApiData.ts if present.",
    currentVisibility: "server-only",
    recommendedFutureVisibility: "server-only",
    classification: "unknown/manual review",
    tooLargeForFrontendUse: false,
    containsDebugReportOrProvenanceFields: false,
    safePublicRemovalCandidate: false,
    futureOwnerApiOrRegistry: "mining recommender API",
    authority: "unknown",
    confidence: "low",
    externalDependency: false,
    validationStatus: "needs-source-audit",
    notes: "A deterministic empty projection is published when the accepted dataset has no location metadata source.",
  },
] as const satisfies readonly GeneratedDataManifestEntry[];

export const generatedDataManifestArchitectureNote = {
  currentState: "public/api is a forbidden data boundary and must remain empty.",
  sourceIngest: "Crafting shaping reads the accepted Scintel snapshot through SCINTEL_DATASET_ROOT, with SCINTEL_COMPONENT_CARD_SOURCE as an explicit override.",
  runtimeDirection: "Browser consumers use routed APIs backed by route-owned server-data registries or user/database state.",
  publicHygiene: "Raw datasets, shaped registries, debug artifacts, reports, and static fallbacks must not be published under public/api.",
  legacyForbiddenPaths: [
    "public/api/**",
    "/api/**/*.json browser URLs",
  ],
  publicationRule: "Raw sources stay in the accepted Scintel snapshot and shaped outputs stay server-only.",
  futureManifestGaps: [
    "Fitting extraction and combat threshold mechanics are not covered as complete generated data domains yet.",
    "SPViewer and Erkul replacement decisions require future manifest entries that identify Foundry authority, external comparison-only sources, and validation status.",
  ],
} as const;
