export type GeneratedDataClassification =
  | "runtime API source data"
  | "canonical generated reference data"
  | "public static fallback data"
  | "server-internal source data"
  | "debug/report artifact"
  | "obsolete/unused candidate"
  | "unknown/manual review";

export type GeneratedDataDomain =
  | "crafting"
  | "FPS crafting"
  | "missions"
  | "mining/recommendations"
  | "lagrange/locations"
  | "refinery";

export type GeneratedDataAuthority =
  | "foundry"
  | "localization"
  | "ref_index"
  | "scintel-inferred"
  | "manual-override"
  | "external-import"
  | "mixed"
  | "unknown";

export type GeneratedDataConfidence = "high" | "medium" | "low" | "needs-validation";

export type GeneratedDataValidationStatus =
  | "not-needed"
  | "needs-source-audit"
  | "needs-mechanics-audit"
  | "needs-ingame-validation"
  | "validated";

export type GeneratedDataManifestEntry = {
  path: string;
  domain: GeneratedDataDomain;
  generatorScript: string;
  sourceInputsSummary: string;
  approximateSize: string;
  runtimeUsage: string;
  currentVisibility: "public/api" | "server-only" | "server-only reference, missing locally";
  recommendedFutureVisibility: "public fallback" | "server-only" | "debug/reports" | "manual review";
  classification: GeneratedDataClassification;
  tooLargeForFrontendUse: boolean;
  containsDebugReportOrProvenanceFields: boolean;
  safePublicRemovalCandidate: boolean;
  futureOwnerApiOrRegistry: string;
  authority: GeneratedDataAuthority;
  confidence: GeneratedDataConfidence;
  externalDependency: boolean;
  externalSources?: readonly string[];
  comparisonSources?: readonly string[];
  validationStatus: GeneratedDataValidationStatus;
  notes?: string;
};

export const generatedDataManifest = [
  {
    path: "public/api/crafting/blueprints.json",
    domain: "crafting",
    generatorScript: "D:/scintel/scripts/link/build_blueprint_api.py",
    sourceInputsSummary: "Foundry vehiclegear blueprint XML, crafted properties, reward pools, localization, material identity.",
    approximateSize: "3.63 MB",
    runtimeUsage: "Fetched by src/lib/craftingData.ts for vehicle crafting recipes.",
    currentVisibility: "public/api",
    recommendedFutureVisibility: "server-only",
    classification: "runtime API source data",
    tooLargeForFrontendUse: true,
    containsDebugReportOrProvenanceFields: true,
    safePublicRemovalCandidate: false,
    futureOwnerApiOrRegistry: "crafting recipe API",
    authority: "mixed",
    confidence: "medium",
    externalDependency: false,
    validationStatus: "needs-source-audit",
    notes: "Foundry-derived with localization and Scintel material identity joins; source authority should be audited before replacing direct public fetches.",
  },
  {
    path: "public/api/crafting/blueprint_rewards.json",
    domain: "crafting",
    generatorScript: "D:/scintel/scripts/link/build_blueprint_api.py",
    sourceInputsSummary: "Foundry crafting blueprint reward pool XML.",
    approximateSize: "0.12 MB",
    runtimeUsage: "No exact runtime fetch found in Moonbreaker.",
    currentVisibility: "public/api",
    recommendedFutureVisibility: "server-only",
    classification: "obsolete/unused candidate",
    tooLargeForFrontendUse: false,
    containsDebugReportOrProvenanceFields: true,
    safePublicRemovalCandidate: true,
    futureOwnerApiOrRegistry: "crafting blueprint source registry",
    authority: "foundry",
    confidence: "high",
    externalDependency: false,
    validationStatus: "not-needed",
    notes: "No exact runtime fetch found; keep only if a future blueprint source registry consumes it.",
  },
  {
    path: "public/api/crafting/component_card_index.json",
    domain: "crafting",
    generatorScript: "D:/scintel/scripts/generate-component-card-index.ts",
    sourceInputsSummary: "Published vehicle/FPS blueprints plus Foundry component stat records and localization.",
    approximateSize: "13.18 MB",
    runtimeUsage: "Fetched by src/lib/componentCardIndex.ts.",
    currentVisibility: "public/api",
    recommendedFutureVisibility: "server-only",
    classification: "runtime API source data",
    tooLargeForFrontendUse: true,
    containsDebugReportOrProvenanceFields: true,
    safePublicRemovalCandidate: false,
    futureOwnerApiOrRegistry: "component card API",
    authority: "mixed",
    confidence: "needs-validation",
    externalDependency: false,
    comparisonSources: ["SPViewer", "Erkul"],
    validationStatus: "needs-source-audit",
    notes: "Foundry stat extraction and fitting/combat mechanics coverage are not complete manifest domains yet; add future entries before SPViewer/Erkul replacement decisions.",
  },
  {
    path: "public/api/crafting/crafted_properties.json",
    domain: "crafting",
    generatorScript: "D:/scintel/scripts/link/build_blueprint_api.py",
    sourceInputsSummary: "Foundry crafting craftedproperties XML.",
    approximateSize: "0.01 MB",
    runtimeUsage: "Fetched by src/lib/craftingData.ts.",
    currentVisibility: "public/api",
    recommendedFutureVisibility: "public fallback",
    classification: "runtime API source data",
    tooLargeForFrontendUse: false,
    containsDebugReportOrProvenanceFields: true,
    safePublicRemovalCandidate: false,
    futureOwnerApiOrRegistry: "crafting property registry",
    authority: "foundry",
    confidence: "high",
    externalDependency: false,
    validationStatus: "not-needed",
  },
  {
    path: "public/api/crafting/quality_quantization.json",
    domain: "crafting",
    generatorScript: "D:/scintel/scripts/link/build_blueprint_api.py and build_mining_material_sources.py",
    sourceInputsSummary: "Foundry crafting qualityquantization XML.",
    approximateSize: "0.04 MB",
    runtimeUsage: "Fetched by crafting and logistics quantization helpers.",
    currentVisibility: "public/api",
    recommendedFutureVisibility: "public fallback",
    classification: "canonical generated reference data",
    tooLargeForFrontendUse: false,
    containsDebugReportOrProvenanceFields: true,
    safePublicRemovalCandidate: false,
    futureOwnerApiOrRegistry: "quality quantization registry",
    authority: "foundry",
    confidence: "needs-validation",
    externalDependency: false,
    validationStatus: "needs-mechanics-audit",
    notes: "Threshold mechanics and quantization interpretation need source/mechanics audit before being treated as final gameplay truth.",
  },
  {
    path: "public/api/crafting/material_quality_quantization.json",
    domain: "crafting",
    generatorScript: "D:/scintel/scripts/link/build_material_quality_quantization.py",
    sourceInputsSummary: "Foundry qualityquantization XML plus mining source material names.",
    approximateSize: "0.01 MB",
    runtimeUsage: "Fetched by build queue and recipe material quality UI.",
    currentVisibility: "public/api",
    recommendedFutureVisibility: "public fallback",
    classification: "runtime API source data",
    tooLargeForFrontendUse: false,
    containsDebugReportOrProvenanceFields: false,
    safePublicRemovalCandidate: false,
    futureOwnerApiOrRegistry: "quality quantization registry",
    authority: "mixed",
    confidence: "needs-validation",
    externalDependency: false,
    validationStatus: "needs-mechanics-audit",
    notes: "User-facing quality options are Foundry-derived but material naming joins come from generated mining/material identity data.",
  },
  {
    path: "public/api/crafting/material_quality_quantization_debug.json",
    domain: "crafting",
    generatorScript: "D:/scintel/scripts/link/build_material_quality_quantization.py",
    sourceInputsSummary: "Foundry qualityquantization XML with raw bands, source paths, warnings, and duplicate-value details.",
    approximateSize: "0.05 MB",
    runtimeUsage: "No runtime fetch found.",
    currentVisibility: "public/api",
    recommendedFutureVisibility: "debug/reports",
    classification: "debug/report artifact",
    tooLargeForFrontendUse: false,
    containsDebugReportOrProvenanceFields: true,
    safePublicRemovalCandidate: true,
    futureOwnerApiOrRegistry: "generated data reports",
    authority: "mixed",
    confidence: "needs-validation",
    externalDependency: false,
    validationStatus: "needs-mechanics-audit",
    notes: "Debug companion for quantization mechanics; should leave public/api when report artifacts are moved.",
  },
  {
    path: "public/api/crafting/material_quality_quantization_report.json",
    domain: "crafting",
    generatorScript: "D:/scintel/scripts/link/build_material_quality_quantization.py",
    sourceInputsSummary: "Quantization generation summary and warnings.",
    approximateSize: "0.00 MB",
    runtimeUsage: "No runtime fetch found.",
    currentVisibility: "public/api",
    recommendedFutureVisibility: "debug/reports",
    classification: "debug/report artifact",
    tooLargeForFrontendUse: false,
    containsDebugReportOrProvenanceFields: true,
    safePublicRemovalCandidate: true,
    futureOwnerApiOrRegistry: "generated data reports",
    authority: "mixed",
    confidence: "needs-validation",
    externalDependency: false,
    validationStatus: "needs-mechanics-audit",
    notes: "Report artifact for quantization generation; not runtime data.",
  },
  {
    path: "public/api/crafting/material_identity_index.json",
    domain: "crafting",
    generatorScript: "D:/scintel/scripts/link/build_material_identity_index.py",
    sourceInputsSummary: "Quantization debug data, mining material sources, carryable entity records, and resource overrides.",
    approximateSize: "0.31 MB",
    runtimeUsage: "Fetched by src/lib/logistics/materialIdentityIndex.ts.",
    currentVisibility: "public/api",
    recommendedFutureVisibility: "public fallback",
    classification: "canonical generated reference data",
    tooLargeForFrontendUse: false,
    containsDebugReportOrProvenanceFields: true,
    safePublicRemovalCandidate: false,
    futureOwnerApiOrRegistry: "material identity registry",
    authority: "mixed",
    confidence: "medium",
    externalDependency: false,
    validationStatus: "needs-source-audit",
    notes: "Combines Foundry references, Scintel inference, and manual override bridges for material identity.",
  },
  {
    path: "public/api/crafting/unresolved_resource_ids.json",
    domain: "crafting",
    generatorScript: "D:/scintel/scripts/link/build_blueprint_api.py",
    sourceInputsSummary: "Unresolved resource ids detected while parsing vehicle blueprints.",
    approximateSize: "0.00 MB",
    runtimeUsage: "No runtime fetch found.",
    currentVisibility: "public/api",
    recommendedFutureVisibility: "debug/reports",
    classification: "debug/report artifact",
    tooLargeForFrontendUse: false,
    containsDebugReportOrProvenanceFields: true,
    safePublicRemovalCandidate: true,
    futureOwnerApiOrRegistry: "generated data reports",
    authority: "scintel-inferred",
    confidence: "medium",
    externalDependency: false,
    validationStatus: "not-needed",
    notes: "Empty unresolved list/report artifact in current output.",
  },
  {
    path: "public/api/crafting/fps/fps_blueprints.json",
    domain: "FPS crafting",
    generatorScript: "D:/scintel/scripts/link/build_fps_crafting_api.py and build_fps_variant_families.py",
    sourceInputsSummary: "Foundry FPS gear blueprint XML, localization, ref index, crafted properties, material identity.",
    approximateSize: "15.55 MB",
    runtimeUsage: "Fetched by src/lib/craftingData.ts for FPS recipes.",
    currentVisibility: "public/api",
    recommendedFutureVisibility: "server-only",
    classification: "runtime API source data",
    tooLargeForFrontendUse: true,
    containsDebugReportOrProvenanceFields: true,
    safePublicRemovalCandidate: false,
    futureOwnerApiOrRegistry: "FPS crafting recipe API",
    authority: "mixed",
    confidence: "medium",
    externalDependency: false,
    comparisonSources: ["SPViewer", "Erkul"],
    validationStatus: "needs-source-audit",
    notes: "Foundry-derived FPS recipes with inferred variant/family metadata; fitting/combat replacement work requires future manifest entries.",
  },
  {
    path: "public/api/crafting/fps/weapons.json",
    domain: "FPS crafting",
    generatorScript: "D:/scintel/scripts/link/build_fps_crafting_api.py and build_fps_variant_families.py",
    sourceInputsSummary: "Weapon subset derived from FPS blueprint records.",
    approximateSize: "3.23 MB",
    runtimeUsage: "No exact runtime fetch found.",
    currentVisibility: "public/api",
    recommendedFutureVisibility: "server-only",
    classification: "obsolete/unused candidate",
    tooLargeForFrontendUse: true,
    containsDebugReportOrProvenanceFields: true,
    safePublicRemovalCandidate: true,
    futureOwnerApiOrRegistry: "FPS crafting recipe API",
    authority: "mixed",
    confidence: "medium",
    externalDependency: false,
    comparisonSources: ["SPViewer", "Erkul"],
    validationStatus: "needs-source-audit",
    notes: "Subset of FPS blueprint data; no exact runtime fetch found.",
  },
  {
    path: "public/api/crafting/fps/armor.json",
    domain: "FPS crafting",
    generatorScript: "D:/scintel/scripts/link/build_fps_crafting_api.py and build_fps_variant_families.py",
    sourceInputsSummary: "Armor subset derived from FPS blueprint records.",
    approximateSize: "12.08 MB",
    runtimeUsage: "No exact runtime fetch found.",
    currentVisibility: "public/api",
    recommendedFutureVisibility: "server-only",
    classification: "obsolete/unused candidate",
    tooLargeForFrontendUse: true,
    containsDebugReportOrProvenanceFields: true,
    safePublicRemovalCandidate: true,
    futureOwnerApiOrRegistry: "FPS crafting recipe API",
    authority: "mixed",
    confidence: "medium",
    externalDependency: false,
    comparisonSources: ["SPViewer", "Erkul"],
    validationStatus: "needs-source-audit",
    notes: "Subset of FPS blueprint data; no exact runtime fetch found.",
  },
  {
    path: "public/api/crafting/fps/ammo.json",
    domain: "FPS crafting",
    generatorScript: "D:/scintel/scripts/link/build_fps_crafting_api.py",
    sourceInputsSummary: "Ammo subset derived from FPS blueprint records.",
    approximateSize: "0.22 MB",
    runtimeUsage: "No exact runtime fetch found.",
    currentVisibility: "public/api",
    recommendedFutureVisibility: "server-only",
    classification: "obsolete/unused candidate",
    tooLargeForFrontendUse: false,
    containsDebugReportOrProvenanceFields: true,
    safePublicRemovalCandidate: true,
    futureOwnerApiOrRegistry: "FPS crafting recipe API",
    authority: "mixed",
    confidence: "medium",
    externalDependency: false,
    comparisonSources: ["SPViewer", "Erkul"],
    validationStatus: "needs-source-audit",
    notes: "Subset of FPS blueprint data; no exact runtime fetch found.",
  },
  {
    path: "public/api/crafting/fps/weapon_families.json",
    domain: "FPS crafting",
    generatorScript: "D:/scintel/scripts/link/build_fps_variant_families.py",
    sourceInputsSummary: "Post-processed visual grouping over FPS weapon blueprint records.",
    approximateSize: "3.47 MB",
    runtimeUsage: "No exact runtime fetch found.",
    currentVisibility: "public/api",
    recommendedFutureVisibility: "server-only",
    classification: "obsolete/unused candidate",
    tooLargeForFrontendUse: true,
    containsDebugReportOrProvenanceFields: true,
    safePublicRemovalCandidate: true,
    futureOwnerApiOrRegistry: "FPS crafting family registry",
    authority: "scintel-inferred",
    confidence: "needs-validation",
    externalDependency: false,
    comparisonSources: ["SPViewer", "Erkul"],
    validationStatus: "needs-source-audit",
    notes: "Visual grouping is inferred, not canonical Foundry authority.",
  },
  {
    path: "public/api/crafting/fps/armor_families.json",
    domain: "FPS crafting",
    generatorScript: "D:/scintel/scripts/link/build_fps_variant_families.py",
    sourceInputsSummary: "Post-processed visual grouping over FPS armor blueprint records.",
    approximateSize: "12.59 MB",
    runtimeUsage: "No exact runtime fetch found.",
    currentVisibility: "public/api",
    recommendedFutureVisibility: "server-only",
    classification: "obsolete/unused candidate",
    tooLargeForFrontendUse: true,
    containsDebugReportOrProvenanceFields: true,
    safePublicRemovalCandidate: true,
    futureOwnerApiOrRegistry: "FPS crafting family registry",
    authority: "scintel-inferred",
    confidence: "needs-validation",
    externalDependency: false,
    comparisonSources: ["SPViewer", "Erkul"],
    validationStatus: "needs-source-audit",
    notes: "Visual grouping is inferred, not canonical Foundry authority.",
  },
  {
    path: "public/api/crafting/fps/fps_variant_families.json",
    domain: "FPS crafting",
    generatorScript: "D:/scintel/scripts/link/build_fps_variant_families.py",
    sourceInputsSummary: "Combined FPS weapon and armor visual family records.",
    approximateSize: "16.06 MB",
    runtimeUsage: "No exact runtime fetch found.",
    currentVisibility: "public/api",
    recommendedFutureVisibility: "server-only",
    classification: "obsolete/unused candidate",
    tooLargeForFrontendUse: true,
    containsDebugReportOrProvenanceFields: true,
    safePublicRemovalCandidate: true,
    futureOwnerApiOrRegistry: "FPS crafting family registry",
    authority: "scintel-inferred",
    confidence: "needs-validation",
    externalDependency: false,
    comparisonSources: ["SPViewer", "Erkul"],
    validationStatus: "needs-source-audit",
    notes: "Visual grouping is inferred, not canonical Foundry authority.",
  },
  {
    path: "public/api/missions/mission_contracts.json",
    domain: "missions",
    generatorScript: "D:/scintel/scripts/link/build_mission_blueprint_rewards_api.py",
    sourceInputsSummary: "Foundry contractgenerator XML, factions, standings, reputation rewards, mission types, blueprint reward pools.",
    approximateSize: "47.70 MB",
    runtimeUsage: "Fetched by src/lib/missionData.ts.",
    currentVisibility: "public/api",
    recommendedFutureVisibility: "server-only",
    classification: "runtime API source data",
    tooLargeForFrontendUse: true,
    containsDebugReportOrProvenanceFields: true,
    safePublicRemovalCandidate: false,
    futureOwnerApiOrRegistry: "mission browser API",
    authority: "mixed",
    confidence: "medium",
    externalDependency: false,
    validationStatus: "needs-source-audit",
    notes: "Foundry contract extraction with localization and blueprint reward joins; too large for direct frontend consumption.",
  },
  {
    path: "public/api/missions/mission_blueprint_rewards.json",
    domain: "missions",
    generatorScript: "D:/scintel/scripts/link/build_mission_blueprint_rewards_api.py",
    sourceInputsSummary: "Blueprint-rewarding mission subset built from contract generators and reward pools.",
    approximateSize: "16.61 MB",
    runtimeUsage: "Fetched by recipe table and blueprint tracker store.",
    currentVisibility: "public/api",
    recommendedFutureVisibility: "server-only",
    classification: "runtime API source data",
    tooLargeForFrontendUse: true,
    containsDebugReportOrProvenanceFields: true,
    safePublicRemovalCandidate: false,
    futureOwnerApiOrRegistry: "blueprint source API",
    authority: "mixed",
    confidence: "medium",
    externalDependency: false,
    validationStatus: "needs-source-audit",
    notes: "Mission-source extraction from Foundry contracts and reward pools; should be shaped by blueprint source APIs.",
  },
  {
    path: "public/api/missions/blueprint_reward_sources.json",
    domain: "missions",
    generatorScript: "D:/scintel/scripts/link/build_mission_blueprint_rewards_api.py",
    sourceInputsSummary: "Reverse lookup from blueprint GUIDs to mission source records.",
    approximateSize: "4.43 MB",
    runtimeUsage: "Fetched by recipe table and blueprint tracker store.",
    currentVisibility: "public/api",
    recommendedFutureVisibility: "server-only",
    classification: "runtime API source data",
    tooLargeForFrontendUse: true,
    containsDebugReportOrProvenanceFields: false,
    safePublicRemovalCandidate: false,
    futureOwnerApiOrRegistry: "blueprint source API",
    authority: "mixed",
    confidence: "medium",
    externalDependency: false,
    validationStatus: "needs-source-audit",
    notes: "Reverse lookup built from mission and blueprint reward joins.",
  },
  {
    path: "public/api/missions/mission_reward_lookups.json",
    domain: "missions",
    generatorScript: "D:/scintel/scripts/link/build_mission_blueprint_rewards_api.py",
    sourceInputsSummary: "Mission lookup tables for blueprint pools, factions, standings, reputation rewards, and mission types.",
    approximateSize: "0.62 MB",
    runtimeUsage: "Fetched by src/lib/missionData.ts.",
    currentVisibility: "public/api",
    recommendedFutureVisibility: "server-only",
    classification: "runtime API source data",
    tooLargeForFrontendUse: false,
    containsDebugReportOrProvenanceFields: true,
    safePublicRemovalCandidate: false,
    futureOwnerApiOrRegistry: "mission browser API",
    authority: "mixed",
    confidence: "medium",
    externalDependency: false,
    validationStatus: "needs-source-audit",
    notes: "Lookup payload mixes Foundry records with localized display labels.",
  },
  {
    path: "public/api/missions/mission_extraction_report.json",
    domain: "missions",
    generatorScript: "D:/scintel/scripts/link/build_mission_blueprint_rewards_api.py",
    sourceInputsSummary: "Mission extraction counts, unresolved references, and validation metadata.",
    approximateSize: "0.01 MB",
    runtimeUsage: "Used only by scripts/validate-public-api.mts.",
    currentVisibility: "public/api",
    recommendedFutureVisibility: "debug/reports",
    classification: "debug/report artifact",
    tooLargeForFrontendUse: false,
    containsDebugReportOrProvenanceFields: true,
    safePublicRemovalCandidate: true,
    futureOwnerApiOrRegistry: "generated data reports",
    authority: "mixed",
    confidence: "medium",
    externalDependency: false,
    validationStatus: "not-needed",
    notes: "Validation/report artifact; not a runtime contract.",
  },
  {
    path: "public/api/recommendations/location_material_index.json",
    domain: "mining/recommendations",
    generatorScript: "D:/scintel/scripts/link/build_mining_static_indexes.py plus scripts/update-pyro-location-indexes.mts",
    sourceInputsSummary: "Enriched mining material sources, spawn edges, Lagrange groups, and localization.",
    approximateSize: "1.18 MB",
    runtimeUsage: "Fetched by src/features/mining/staticMiningIndex.ts.",
    currentVisibility: "public/api",
    recommendedFutureVisibility: "public fallback",
    classification: "public static fallback data",
    tooLargeForFrontendUse: true,
    containsDebugReportOrProvenanceFields: true,
    safePublicRemovalCandidate: false,
    futureOwnerApiOrRegistry: "mining recommender API",
    authority: "mixed",
    confidence: "needs-validation",
    externalDependency: false,
    validationStatus: "needs-mechanics-audit",
    notes: "Includes Scintel-inferred class resolution, source probability, method fit, and quality signals; scoring/threshold mechanics need audit.",
  },
  {
    path: "public/api/recommendations/material_encounter_rankings.json",
    domain: "mining/recommendations",
    generatorScript: "D:/scintel/scripts/link/build_mining_static_indexes.py plus scripts/update-pyro-location-indexes.mts",
    sourceInputsSummary: "Ranked material/location rows derived from static mining indexes.",
    approximateSize: "0.33 MB",
    runtimeUsage: "Fetched by src/features/mining/staticMiningIndex.ts.",
    currentVisibility: "public/api",
    recommendedFutureVisibility: "public fallback",
    classification: "public static fallback data",
    tooLargeForFrontendUse: false,
    containsDebugReportOrProvenanceFields: false,
    safePublicRemovalCandidate: false,
    futureOwnerApiOrRegistry: "mining recommender API",
    authority: "scintel-inferred",
    confidence: "needs-validation",
    externalDependency: false,
    validationStatus: "needs-mechanics-audit",
    notes: "Ranking fields are derived from Scintel scoring and should be validated against intended mining mechanics.",
  },
  {
    path: "public/api/recommendations/material_quality_index.json",
    domain: "mining/recommendations",
    generatorScript: "D:/scintel/scripts/link/build_mining_static_indexes.py plus scripts/update-pyro-location-indexes.mts",
    sourceInputsSummary: "Material quality chance rows derived from static mining indexes.",
    approximateSize: "0.20 MB",
    runtimeUsage: "Fetched by src/features/mining/staticMiningIndex.ts.",
    currentVisibility: "public/api",
    recommendedFutureVisibility: "public fallback",
    classification: "public static fallback data",
    tooLargeForFrontendUse: false,
    containsDebugReportOrProvenanceFields: false,
    safePublicRemovalCandidate: false,
    futureOwnerApiOrRegistry: "mining recommender API",
    authority: "mixed",
    confidence: "needs-validation",
    externalDependency: false,
    validationStatus: "needs-mechanics-audit",
    notes: "Quality thresholds are generated estimates; source and mechanics validation are still required.",
  },
  {
    path: "public/api/recommendations/location_distribution_index.json",
    domain: "mining/recommendations",
    generatorScript: "D:/scintel/scripts/link/build_mining_static_indexes.py plus scripts/update-pyro-location-indexes.mts",
    sourceInputsSummary: "Location mining-class distribution rows derived from spawn edges.",
    approximateSize: "0.03 MB",
    runtimeUsage: "Fetched by src/features/mining/staticMiningIndex.ts.",
    currentVisibility: "public/api",
    recommendedFutureVisibility: "public fallback",
    classification: "public static fallback data",
    tooLargeForFrontendUse: false,
    containsDebugReportOrProvenanceFields: false,
    safePublicRemovalCandidate: false,
    futureOwnerApiOrRegistry: "mining recommender API",
    authority: "scintel-inferred",
    confidence: "needs-validation",
    externalDependency: false,
    validationStatus: "needs-mechanics-audit",
    notes: "Location method distribution is derived from spawn edges and class resolver logic.",
  },
  {
    path: "public/api/recommendations/location_hierarchy_index.json",
    domain: "mining/recommendations",
    generatorScript: "D:/scintel/scripts/link/build_mining_static_indexes.py",
    sourceInputsSummary: "Generated Lagrange groups folded into mining location hierarchy metadata.",
    approximateSize: "0.00 MB",
    runtimeUsage: "Fetched by src/features/mining/staticMiningIndex.ts.",
    currentVisibility: "public/api",
    recommendedFutureVisibility: "public fallback",
    classification: "public static fallback data",
    tooLargeForFrontendUse: false,
    containsDebugReportOrProvenanceFields: false,
    safePublicRemovalCandidate: false,
    futureOwnerApiOrRegistry: "mining recommender API",
    authority: "mixed",
    confidence: "medium",
    externalDependency: false,
    validationStatus: "needs-source-audit",
    notes: "Hierarchy folds generated Lagrange grouping into mining indexes.",
  },
  {
    path: "public/api/lagrange-groups.generated.json",
    domain: "lagrange/locations",
    generatorScript: "D:/scintel/scripts/generate-lagrange-api.mjs",
    sourceInputsSummary: "Localization global.ini grouped by Lagrange material signatures.",
    approximateSize: "0.01 MB",
    runtimeUsage: "Fetched by src/features/locations/stantonLagrangeChildren.ts.",
    currentVisibility: "public/api",
    recommendedFutureVisibility: "public fallback",
    classification: "public static fallback data",
    tooLargeForFrontendUse: false,
    containsDebugReportOrProvenanceFields: true,
    safePublicRemovalCandidate: false,
    futureOwnerApiOrRegistry: "location registry",
    authority: "localization",
    confidence: "medium",
    externalDependency: false,
    validationStatus: "needs-source-audit",
    notes: "Generated grouping uses localization labels and inferred material signatures; should be audited before becoming canonical location authority.",
  },
  {
    path: "public/api/lagrange-children.generated.json",
    domain: "lagrange/locations",
    generatorScript: "D:/scintel/scripts/generate-lagrange-api.mjs",
    sourceInputsSummary: "Scintel ref_index StarMapObject records for Lagrange point children.",
    approximateSize: "0.37 MB",
    runtimeUsage: "Fetched by src/features/locations/stantonLagrangeChildren.ts.",
    currentVisibility: "public/api",
    recommendedFutureVisibility: "public fallback",
    classification: "public static fallback data",
    tooLargeForFrontendUse: false,
    containsDebugReportOrProvenanceFields: true,
    safePublicRemovalCandidate: false,
    futureOwnerApiOrRegistry: "location registry",
    authority: "ref_index",
    confidence: "medium",
    externalDependency: false,
    validationStatus: "needs-source-audit",
    notes: "Derived from ref_index StarMapObject records; includes provenance paths.",
  },
  {
    path: "public/api/refinery/refinery_yields.json",
    domain: "refinery",
    generatorScript: "scripts/import-refinery-yields.mts",
    sourceInputsSummary: "UEX refinery yields CSV.",
    approximateSize: "0.01 MB",
    runtimeUsage: "Fetched by src/lib/refineryData.ts.",
    currentVisibility: "public/api",
    recommendedFutureVisibility: "public fallback",
    classification: "canonical generated reference data",
    tooLargeForFrontendUse: false,
    containsDebugReportOrProvenanceFields: true,
    safePublicRemovalCandidate: false,
    futureOwnerApiOrRegistry: "refinery planner API",
    authority: "external-import",
    confidence: "needs-validation",
    externalDependency: true,
    externalSources: ["UEX", "manual CSV"],
    validationStatus: "needs-source-audit",
    notes: "Imported from a UEX CSV rather than Foundry authority; should be cross-checked before canonical gameplay claims.",
  },
  {
    path: "D:/scintel/api/recommendations/material_source_scores.json",
    domain: "mining/recommendations",
    generatorScript: "D:/scintel/scripts/link/build_material_source_scores.py",
    sourceInputsSummary: "Mining material_sources.json, mineables.json, and location_material_index.json.",
    approximateSize: "0.55 MB",
    runtimeUsage: "Read by server/config/apiPaths.ts and server/recommender/loadApiData.ts.",
    currentVisibility: "server-only",
    recommendedFutureVisibility: "server-only",
    classification: "server-internal source data",
    tooLargeForFrontendUse: false,
    containsDebugReportOrProvenanceFields: true,
    safePublicRemovalCandidate: false,
    futureOwnerApiOrRegistry: "mining recommender API",
    authority: "scintel-inferred",
    confidence: "needs-validation",
    externalDependency: false,
    validationStatus: "needs-mechanics-audit",
    notes: "Server-only scored recommender source; scoring model should remain auditable separately from public static fallback files.",
  },
  {
    path: "D:/scintel/api/mining/material_sources_quality_enriched.json",
    domain: "mining/recommendations",
    generatorScript: "D:/scintel/scripts/link/enrich_material_source_quality.py",
    sourceInputsSummary: "Mining material_sources.json enriched with quality_distribution.json.",
    approximateSize: "1.49 MB",
    runtimeUsage: "Read by server/config/apiPaths.ts and server/recommender/loadApiData.ts.",
    currentVisibility: "server-only",
    recommendedFutureVisibility: "server-only",
    classification: "server-internal source data",
    tooLargeForFrontendUse: true,
    containsDebugReportOrProvenanceFields: true,
    safePublicRemovalCandidate: false,
    futureOwnerApiOrRegistry: "mining recommender API",
    authority: "mixed",
    confidence: "needs-validation",
    externalDependency: false,
    validationStatus: "needs-mechanics-audit",
    notes: "Quality enrichment combines Foundry quality distributions with Scintel matching heuristics.",
  },
  {
    path: "D:/scintel/api/recommendations/location_metadata.json",
    domain: "mining/recommendations",
    generatorScript: "unknown/manual review",
    sourceInputsSummary: "Referenced by server/config/apiPaths.ts; file was not present in the audited D:/scintel/api listing.",
    approximateSize: "unknown",
    runtimeUsage: "Read by server/recommender/loadApiData.ts if present.",
    currentVisibility: "server-only reference, missing locally",
    recommendedFutureVisibility: "manual review",
    classification: "unknown/manual review",
    tooLargeForFrontendUse: false,
    containsDebugReportOrProvenanceFields: false,
    safePublicRemovalCandidate: false,
    futureOwnerApiOrRegistry: "mining recommender API",
    authority: "unknown",
    confidence: "low",
    externalDependency: false,
    validationStatus: "needs-source-audit",
    notes: "Referenced by server config but absent from the audited local Scintel API listing.",
  },
] as const satisfies readonly GeneratedDataManifestEntry[];

export const generatedDataManifestArchitectureNote = {
  currentState: "public/api contains generated static reference files, not true shaped API responses.",
  futureDirection: "Future shaped API endpoints should consume generated data server-side and return smaller route-specific responses.",
  publicHygiene: "Debug and report artifacts should move out of public/api.",
  largeFiles: [
    "public/api/missions/mission_contracts.json",
    "public/api/missions/mission_blueprint_rewards.json",
    "public/api/crafting/fps/fps_blueprints.json",
    "public/api/crafting/component_card_index.json",
  ],
  largeFileRecommendation: "Large direct-fetch files should become server-only once shaped APIs replace frontend static JSON fetches.",
  futureManifestGaps: [
    "Fitting extraction and combat threshold mechanics are not covered as complete generated data domains yet.",
    "SPViewer and Erkul replacement decisions require future manifest entries that identify Foundry authority, external comparison-only sources, and validation status.",
  ],
} as const;
